image: Visual Studio 2017

platform:
  - x86

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12.13.0
  - yarn

build_script:
  - set
  - yarn make
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - dir out
  - dir out\make
  - dir out\make\squirrel.windows

test: off

artifacts:
  - path: 'out\make\**\*.*'

before_deploy:
  - ps: |
          $GITLAB_PROJECT_ID = $env:GITLAB_PROJECT_ID           
          $GITLAB_API_TOKEN = $env:GITLAB_API_TOKEN
          $url = "https://gitlab.com/api/v4/projects/$GITLAB_PROJECT_ID/uploads"
          $webClient = New-Object System.Net.webClient
          $webClient.Headers.Add("PRIVATE-TOKEN", "$GITLAB_API_TOKEN") 


          $artifacts = gci .\out\make -Recurse | ?{ $_.PSIsContainer -eq $false } 
          [System.Collections.ArrayList]$files = @()
          foreach ($artifact in $artifacts) { 
              Write-Host ""
              Write-Host "****************************************"
              Write-Host "Artifact name  : $($artifact.Name)"
              Write-Host "Artifact path  : $($artifact.Fullname)"
              Write-Host "****************************************"
              
              $file = New-Object -TypeName psobject
              Write-Host "[+] Uploading artifact $($artifact.name)"
              # $res = (curl --request POST --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}"  --form "file=@$($artifact.Fullname)" https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/uploads)
              #upload

              $bytes = $WebClient.UploadFile($url, "POST", $Filename.fullname)
              $text = [System.Text.Encoding]::ASCII.GetString($bytes) 
              $jRes = $text | ConvertFrom-json


              Write-Host "Upload result : "
              $jRes

              $file | Add-Member -MemberType NoteProperty -Name "name" -Value "$($jRes.alt)"
              $file | Add-Member -MemberType NoteProperty -Name "url" -Value "https://gitlab.com$($jRes.url)"

              $files.Add($file)

          }
          $files|ft

          Write-Host "[+] Generating Release"

          

