image: Visual Studio 2017

platform:
  - x64

build_script:
  # useful for debugging
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test: off

artifacts:
  - path: 'out\make\**\*.*'