image: Visual Studio 2017

platform:
  - x86
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12.13.0 x86
  - yarn

build_script:
  - dir
  - yarn make
  - dir out
  - dir out\make
  - dir out\make\squirrel.windows

test: off

artifacts:
  - path: 'out\make\**\*.*'
    name: MyApp
