image: Visual Studio 2017

platform:
  - x86
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12.13.0
  - yarn

build_script:
  - set
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - yarn make
  - dir out
  - dir out\make
  - dir out\make\squirrel.windows

test: off

artifacts:
  - path: 'out\make\**\*.*'
    name: MyApp
