site_name: Hurry Documentation
site_description: 'Documentation about Hurry IT Admin Tool'
site_author: 'rebrec'
site_url: 'https://rebrec.github.io/hurry/'
docs_dir: docs/
repo_name: 'rebrec/hurry'
repo_url: 'https://github.com/rebrec/hurry'
edit_uri: 'docs/'
nav:
    - Home: README.md
    - Getting Started:
      - Install and configure: guides/getting-started/install-and-configure/install-and-configure.md
      - Install a plugin: guides/getting-started/install-a-plugin/install-a-plugin.md
    - Setup your build environment: guides/setup-the-build-environment/setup-the-build-environment.md
    - Plugins:
      - First Plugin: guides/plugins/first-plugin/first-plugin.md
theme:
  name: 'material'
markdown_extensions:
  - codehilite:
      guess_lang: true
      use_pygments: true