site_name: Hurry Documentation
site_description: 'Documentation about Hurry IT Admin Tool'
site_author: 'rebrec'
docs_dir: docs/
repo_name: 'rebrec/hurry'
repo_url: 'https://github.com/rebrec/hurry'
nav:
    - Home: README.md
    - Getting Started:
      - Install and configure: guides/getting-started/install-and-configure.md
      - Install a plugin: guides/getting-started/install-a-plugin.md
    - Setup your build environment: guides/setup-the-build-environment/setup-the-build-environment.md
theme:
  name: 'material'
